// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/alunos": {
            "get": {
                "description": "Exibe todos os alunos",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Alunos"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Aluno"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Cria um novo aluno",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Alunos"
                ],
                "parameters": [
                    {
                        "description": "Aluno object",
                        "name": "aluno",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Aluno"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Aluno"
                            }
                        }
                    }
                }
            }
        },
        "/alunos/{id}": {
            "get": {
                "description": "Realiza uma busca baseada pelo ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Alunos"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Aluno"
                        }
                    }
                }
            },
            "delete": {
                "description": "Realiza uma busca baseada pelo ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Alunos"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "patch": {
                "description": "Realiza uma edição baseada pelo ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Alunos"
                ],
                "parameters": [
                    {
                        "description": "Aluno object",
                        "name": "aluno",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Aluno"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/alunos/{nome}": {
            "get": {
                "description": "Realiza uma busca baseada pelo Nome",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Alunos"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Aluno"
                        }
                    }
                }
            }
        },
        "/professores": {
            "get": {
                "description": "Exibe todos os professores",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Professores"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Professor"
                            }
                        }
                    }
                }
            }
        },
        "/professores/{id}": {
            "delete": {
                "description": "Realiza uma busca baseada pelo ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Professores"
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            },
            "patch": {
                "description": "Realiza uma edição baseada pelo ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Professores"
                ],
                "parameters": [
                    {
                        "description": "Professor object",
                        "name": "professor",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Professor"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/professores/{nome}": {
            "get": {
                "description": "Realiza uma busca baseada pelo Nome",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Professores"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Professor"
                        }
                    }
                }
            }
        },
        "/professors": {
            "post": {
                "description": "Cria um novo professor",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Professores"
                ],
                "parameters": [
                    {
                        "description": "Professor object",
                        "name": "professor",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Professor"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Professor"
                            }
                        }
                    }
                }
            }
        },
        "/professors/{id}": {
            "get": {
                "description": "Realiza uma busca baseada pelo ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Professores"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Professor"
                        }
                    }
                }
            }
        },
        "/questoes": {
            "post": {
                "description": "Cria uma nova Questao",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Questoes"
                ],
                "parameters": [
                    {
                        "description": "Questao object",
                        "name": "questao",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Questao"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Questao"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "gorm.DeletedAt": {
            "type": "object",
            "properties": {
                "time": {
                    "type": "string"
                },
                "valid": {
                    "description": "Valid is true if Time is not NULL",
                    "type": "boolean"
                }
            }
        },
        "models.Alternativa": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "id": {
                    "type": "integer"
                },
                "resposta": {
                    "type": "boolean"
                },
                "texto": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "models.Aluno": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "data_nascimento": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "id": {
                    "type": "integer"
                },
                "nome": {
                    "type": "string"
                },
                "turma_id": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.Professor": {
            "type": "object",
            "properties": {
                "contato": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "especializacao": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "nome": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "models.Questao": {
            "type": "object",
            "properties": {
                "alternativas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Alternativa"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "$ref": "#/definitions/gorm.DeletedAt"
                },
                "enunciado": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "materia_id": {
                    "type": "integer"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Test API",
	Description:      "A Test API using GO, Gin and Gorm",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
