definitions:
  gin.H:
    additionalProperties: {}
    type: object
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  models.Alternativa:
    properties:
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      resposta:
        type: boolean
      texto:
        type: string
      updatedAt:
        type: string
    type: object
  models.Aluno:
    properties:
      createdAt:
        type: string
      data_nascimento:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      nome:
        type: string
      turma_id:
        type: integer
      updatedAt:
        type: string
      user_id:
        type: integer
    type: object
  models.Professor:
    properties:
      contato:
        type: string
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      especializacao:
        type: string
      id:
        type: integer
      nome:
        type: string
      updatedAt:
        type: string
      user_id:
        type: integer
    type: object
  models.Questao:
    properties:
      alternativas:
        items:
          $ref: '#/definitions/models.Alternativa'
        type: array
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      enunciado:
        type: string
      id:
        type: integer
      materia_id:
        type: integer
      updatedAt:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: A Test API using GO, Gin and Gorm
  title: Test API
  version: "1.0"
paths:
  /alternativas/{questao_id}:
    get:
      parameters:
      - description: Question ID
        format: uuid
        in: path
        name: questao_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Alternativa'
            type: array
      summary: List alternatives for a question
      tags:
      - Alternativas
  /alunos:
    get:
      parameters:
      - description: Nome do aluno a ser buscado
        in: query
        name: nome
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Aluno'
            type: array
      summary: Busca alunos pelo Nome
      tags:
      - Alunos
    post:
      parameters:
      - description: Objeto Aluno a ser criado
        in: body
        name: aluno
        required: true
        schema:
          $ref: '#/definitions/models.Aluno'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Aluno'
      summary: Cria um novo aluno
      tags:
      - Alunos
  /alunos/{id}:
    delete:
      parameters:
      - description: ID do aluno a ser deletado
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
      summary: Deleta um aluno pelo ID
      tags:
      - Alunos
    get:
      parameters:
      - description: ID do aluno
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Aluno'
      summary: Busca um aluno pelo ID
      tags:
      - Alunos
    patch:
      parameters:
      - description: ID do aluno a ser editado
        in: path
        name: id
        required: true
        type: string
      - description: Objeto Aluno com as alterações
        in: body
        name: aluno
        required: true
        schema:
          $ref: '#/definitions/models.Aluno'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Aluno'
      summary: Edita um aluno pelo ID
      tags:
      - Alunos
  /professores:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Professor'
            type: array
      summary: Lista todos os professores
      tags:
      - Professores
    post:
      parameters:
      - description: Objeto Professor a ser criado
        in: body
        name: professor
        required: true
        schema:
          $ref: '#/definitions/models.Professor'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Professor'
      summary: Cria um novo professor
      tags:
      - Professores
  /professores/{id}:
    delete:
      parameters:
      - description: ID do professor a ser deletado
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
      summary: Deleta um professor pelo ID
      tags:
      - Professores
    get:
      parameters:
      - description: ID do professor
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Professor'
      summary: Busca um professor pelo ID
      tags:
      - Professores
    patch:
      parameters:
      - description: ID do professor a ser editado
        in: path
        name: id
        required: true
        type: string
      - description: Objeto Professor com as alterações
        in: body
        name: professor
        required: true
        schema:
          $ref: '#/definitions/models.Professor'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Professor'
      summary: Edita um professor pelo ID
      tags:
      - Professores
  /professores/{nome}:
    post:
      parameters:
      - description: Nome do professor a ser buscado
        in: query
        name: nome
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Professor'
            type: array
      summary: Busca professores pelo Nome
      tags:
      - Professores
  /questoes:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Questao'
            type: array
      summary: Exibe todas as Questoes
      tags:
      - Questoes
    post:
      parameters:
      - description: Objeto Questao a ser criado
        in: body
        name: questao
        required: true
        schema:
          $ref: '#/definitions/models.Questao'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Questao'
      summary: Cria uma nova Questao
      tags:
      - Questoes
swagger: "2.0"
